# Generated by Django 3.1.2 on 2021-02-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0002_auto_20210227_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR_Functionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employee_Details', models.CharField(blank=True, max_length=500, null=True)),
                ('Meeting', models.CharField(blank=True, max_length=500, null=True)),
                ('Attedence', models.CharField(blank=True, max_length=500, null=True)),
                ('PunchIn_PunchOut', models.CharField(blank=True, max_length=500, null=True)),
                ('EOD', models.CharField(blank=True, max_length=500, null=True)),
                ('Notification', models.CharField(blank=True, max_length=500, null=True)),
                ('Salary_Details', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(blank=True, max_length=50, null=True)),
                ('leave_application', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
