# Generated by Django 3.0.6 on 2021-03-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HR', '0006_add_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_employee',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='add_employee',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='employee_registration',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee_registration',
            old_name='lname',
            new_name='last_name',
        ),
    ]
